dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: XRpY/DnOEWXSPHnkVmOZfXfzBHXuI+5d0vkyKIHcH3XbQn3uwqfHdUBYQ8XthOg8RLh7MWAy6ZpAwLshr2hcijlBA4QkAAcWDHoetN4RjVE/BE6ha3h8Y6uyAjrUFRdR3PdnefeJ6p+5u3CzwuGXvFTD/8pW4arOSDGsbMut61510gRO6uWLFEhzJdIEFnV0SQ0v1FvVvEFDNCA3vnVtxCdughxnRkTorcmeDaiQeEq4oqO/5d+j0Y9+riwlB3wENWY96WSCXhCXpl0XXO+zITSJ0CEehU77ijsOk0AAmcKdJKIlTpMboMRuC9sGx0dhpel47pT76+yH6bWNaP0M+XCYaT2ZkADN3nmubb0TIl85Tm3737urCKS9cYCiT1GZ2eRISAR17YMGjcLHjHbLUGBOHbB+CVE1/uU2wHGamsWGe1H1UpNBoVoCqjWc45kT5YUttWdZwWMssgrKjxNawx+8F8F+2kkQ/5VA93UYKjs8jvkNBjEOhAYZ7S0DJszyHM2vcGJCDPCS5kzhWBWVdqnn0pARRM+mtlFOEh4qO2Txln2aGapg77vD9lJgB+LmHkFG3CLirYRHdvNrKlaM9qxDVi9Q2GPwYOjAJH5286xQDGBZ93fWcEukFzjyt4IsE84tBLY3+ToXvIni0zM7fcKQMmE63gC8BruUr0ahqrE=
