---
- name: Install Docker
  hosts: all
  vars:
    CONTAINER_NAME: 'dmitrykorlas/otus-reddit:1.0'
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Start containerized monolith app
      docker_container:
        name: reddit
        image: "{{ CONTAINER_NAME }}"
        state: started
        ports:
          - "9292:9292"
          - "80:80"
