version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
  ui:
    build: ../src/ui
    # uncomment to use custom name of container
    # container_name: app_ui
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - "${UI_PORT}:9292"
    networks:
      - front_net
volumes:
  post_db:


networks:
  back_net:
    internal: true
  front_net:
