version: '3.3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net
      - front_net

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      # single-node mode for testing and development
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - back_net
      - front_net

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
#    environment:
#       # single-node mode for testing and development
#      - discovery.type=single-node
    networks:
      - back_net
      - front_net

networks:
  back_net:
    internal: true
  front_net:
