version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  post:
    # build: ../src/post-py
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    depends_on:
      - fluentd
    networks:
      - back_net
      - front_net

  comment:
    # build: ../src/comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net

  ui:
    # build: ../src/ui
    # uncomment to use custom name of container
    # container_name: app_ui
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "${UI_PORT}:9292"
    networks:
      - front_net

## use to have uncotigorized logs
#  ui:
#    image: artemmkin/ui
#    environment:
#      - POST_SERVICE_HOST=post
#      - POST_SERVICE_PORT=5000
#      - COMMENT_SERVICE_HOST=comment
#      - COMMENT_SERVICE_PORT=9292
#    ports:
#      - "9292:9292"
#    depends_on:
#      - post
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: service.ui
#    networks:
#      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    internal: true
  front_net:
