{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "response time 95 percentile",
   "type": "graph",
   "description": "Displays 95 percentile for response time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "UI HTTP requests",
   "type": "graph",
   "description": "All HTTP requests thats UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"[123].*\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"[45].*\"}[1m])"
    }
   ]
  }
 ]
}