resource google_compute_instance "app" {
  count        = var.instances_amount
  name         = "docker-monolith-${count.index}"
  machine_type = "g1-small"
  zone         = var.zone
  tags         = ["docker-monolith-app"]
  metadata = {
    ssh-keys = "appuser:${file(var.public_key_path)}"
  }

  connection {
    type        = "ssh"
    host        = self.network_interface[0].access_config[0].nat_ip
    user        = "appuser"
    agent       = false
    private_key = file(var.private_key_path)
  }

  boot_disk {
    initialize_params { image = var.app_disk_image }
  }

  network_interface {
    network = "default"

    # this part is optional (and google_compute_address too),
    # seems it just to use a named IP vs IP with autogenerated name
    access_config {
      nat_ip = google_compute_address.app_ip[count.index].address
    }
  }
}

resource "google_compute_address" "app_ip" {
  count = var.instances_amount
  name  = "reddit-app-ip-${count.index}"
}

resource "google_compute_firewall" "firewall_puma" {
  name    = "allow-puma-default"
  network = "default"
  allow {
    protocol = "tcp"
    ports    = ["9292", "80"]
  }
  source_ranges = ["0.0.0.0/0"]
  # this firewall rule will be applicable for instances with the tags listed in "target_tags"
  target_tags = ["docker-monolith-app"]
}
